os: linux
language: bash
sudo: required
services:
- docker
dist: bionic
script: ./ci/build-and-push-latest.sh
branches:
  only:
  - master
matrix:
  include:
  - env:
      DOCKER_FILE: docker_images/Dockerfile.clefos-7
      DOCKER_BUILD_TAG: clefos-7
  - env:
      DOCKER_FILE: docker_images/Dockerfile.centos-7
      DOCKER_BUILD_TAG: centos-7
  - env:
      DOCKER_FILE: docker_images/Dockerfile.debian-stretch
      DOCKER_BUILD_TAG: debian-stretch
  - env:
      DOCKER_FILE: docker_images/Dockerfile.fedora-24
      DOCKER_BUILD_TAG: fedora-24
  - env:
      DOCKER_FILE: docker_images/Dockerfile.fedora-25
      DOCKER_BUILD_TAG: fedora-25
  - env:
      DOCKER_FILE: docker_images/Dockerfile.fedora-26
      DOCKER_BUILD_TAG: fedora-26
  - env:
      DOCKER_FILE: docker_images/Dockerfile.fedora-27
      DOCKER_BUILD_TAG: fedora-27
  - env:
      DOCKER_FILE: docker_images/Dockerfile.fedora-28
      DOCKER_BUILD_TAG: fedora-28
  - env:
      DOCKER_FILE: docker_images/Dockerfile.fedora-29
      DOCKER_BUILD_TAG: fedora-29
  - env:
      DOCKER_FILE: docker_images/Dockerfile.fedora-30
      DOCKER_BUILD_TAG: fedora-30
  - env:
      DOCKER_FILE: docker_images/Dockerfile.fedora-31
      DOCKER_BUILD_TAG: fedora-31
  - env:
      DOCKER_FILE: docker_images/Dockerfile.fedora-32
      DOCKER_BUILD_TAG: fedora-32
  - env:
      DOCKER_FILE: docker_images/Dockerfile.ubuntu-xenial
      DOCKER_BUILD_TAG: ubuntu-xenial
  - env:
      DOCKER_FILE: docker_images/Dockerfile.ubuntu-bionic
      DOCKER_BUILD_TAG: ubuntu-bionic
  - env:
      DOCKER_FILE: docker_images/Dockerfile.ubuntu-trusty
      DOCKER_BUILD_TAG: ubuntu-trusty
  - env:
      DOCKER_FILE: docker_images/Dockerfile.ubuntu-focal
      DOCKER_BUILD_TAG: ubuntu-focal
env:
  global:
  - RUNAGAIN=yes
  - DOCKER_IMAGE=ansible
  - DOCKER_REGISTRY=bendermibm
notifications:
  slack:
    secure: PLp4khYLUpMRqsMCN/e2RZytVE+lPPoVjmDhh4opsig2F2/eyKrm83IYkgkvg74p0PIXxu0iYanhsSHc9M9dM09mme4LT8x11AZdxWLu0RaNtjMm/1nST9N2jgNgzVtccSEpoEWSSAsBVRVUKmIqK4cOCKNDcmJ9IODhE8f5QUK/u0NNZZzXhhreV17Q3QaBZkQhOB6gCcmSTnOYf0W+wWi2H5ICdlYOKPW2iqmTjz+M4aQeuX0X+hRg3voqrCcwy2AVIImxs3b33xBJbVKFG9+a0vsM4/fnYAE6meowtgJu8nigCCVTLYiudp5NCWJZW8WV9Cgg5CQrXFIoVo7LsmNI7hNAQkvfZVOUKcn0YFnBjyvEEPnBqJhbg+hw5Tsjt6ZkFywTBTgIIRl4if7/uAVARn9hoKB+asTvaPw1s21JONwzLqV0CRb9NC2z+M+B/CNYjpub1IWLy+H6g3ijX1agbaRy4Lw9WU/bnDhKcEkszXbBoFzKrY/YluiA9+PRhUZWEX9JJO+Mi8WGWLAhT6P/y8PHYbT6GCR8jHZ1HV5Q0BIy37C1hGrOSv3Ur+oXHtBmzqpUAxBtLW9cgE27s0WySwhlJT48pEBqnUn937mXoAQexBIq883119l2fkgTxqYUNxSkUsIYL6g8RNv6ENTH31NZH4kPek4HpKuaPuU=
    template:
    - Build <%{build_url}|#%{build_number}> (<%{compare_url}|%{commit}>) of %{repository_slug}@%{branch}
      by %{author} %{result} in %{duration}. ```sys-ltic-docker-local.artifactory.swg-devops.com/%{docker_image}:%{build_id}```
